[workspace]

members = [
  "tower",
  "tower-balance",
  "tower-blocking-service",
  "tower-buffer",
  "tower-discover",
  "tower-filter",
  "tower-in-flight-limit",
  "tower-mock",
  "tower-layer",
  "tower-rate-limit",
  "tower-reconnect",
  "tower-retry",
  "tower-service",
  "tower-service-util",
  "tower-timeout",
]
